### DISCUSSION TITLE
Initial Install on Azure

### DISCUSSION THREAD

**Discussion by erick-prosimo** [terrakube-io/terrakube#298] [Q&A] [answered]
There seem to be a handful of steps that are not called out in the documentation. For people who work with these things every day it may be obvious, but it is unclear for those who do not. Take for example the initial helm charts. There are a lot of values like this: https://terrakube-ui.domain.com

It would be advisable to walk through changing the service ingress to "LoadBalancer" along with populating the generated public IP's to support external connectivity. Just deploying the helm chart as-is will leave the service inaccessible.

**Comment by alfespa17** [comment, marked as answer]
Hello @erick-prosimo, I understand your point there are like different parameters that you need to change in order to make the installation work. 

For the domain that you need to update I was thinking maybe just leaving one parameter asking the domain that you will use and create some output in the helm chart with the URLs for the api, registry, dex component, etc instead of filling all the URL in the helm chart values.

Example
```yaml
domain: myterrakube.com
```

And in the helm chart output could be something like this.
```bash
Your terrakube installation is complete the URLs will be the following:

Api: terrakube-api.myterrakube.com
Registry: terrakube-reg.myterrakube.com
Dex: terrakube-api.myterrakube.com/dex

```

But there are other parameters I am not really sure what could be the best practice becuase there are like several configuration options depending of where you are installing terrakube this is the reason we left like several [examples](https://github.com/AzBuilder/terrakube-helm-chart#4-build-yaml-file) in the helm chart repository.

All suggestions, ideas are welcome even if you want to contribute feel free to send the pull request to improve the documentation.

**Reply by erick-prosimo** [reply]
Yes, totally understand that is almost impossible to show all options/combinations. As I don't work with K8s every day though I will say I cannot get Terrakube working. I can install the helm chart, but then what? I tried setting LoadBalancer as the ingress so the services would be publicly accessible, I tried adding external DNS resolution to the domain names, but it still wont connect. I have updated the re-direct URI for the AAD app, but nothing seems to work.

**Reply by alfespa17** [reply]
Hello @erick-prosimo I can help with the setup

Can you provide some information about the cluster? are you using AKS? ngnix ingress?

The first step will be to have one AKS cluster with some ingress installed and working (for example ngnix). 

Do you have that setup completed?

Microsoft provide some guide to setup the ingress using AKS. [Reference](https://learn.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli)

**Reply by erick-prosimo** [reply]
Deploying the helm chart when changing the api/ui to LoadBalancer it looks like we created some ingress: 
![image](https://user-images.githubusercontent.com/100948345/215846831-bd565461-70b4-4a1a-9259-25907d424a48.png)

**Reply by alfespa17** [reply]
Could you check the following:

Deployment:
![image](https://user-images.githubusercontent.com/4461895/215857915-8a7ea17c-1cf6-411e-a485-0720fc624c11.png)

Pods:
![image](https://user-images.githubusercontent.com/4461895/215857959-6f3ac573-3da8-400f-b74a-c913a2751349.png)

Services Terrakube:
![image](https://user-images.githubusercontent.com/4461895/215858067-4832c363-aa27-430d-b092-65c971092334.png)

Services Ngnix:
![image](https://user-images.githubusercontent.com/4461895/215859611-3a37402f-ba2e-4526-9c36-0ecdd899b6c7.png)

Ingress:
![image](https://user-images.githubusercontent.com/4461895/215858407-e52a800e-6a8a-497f-ba1a-233c89fc248b.png)

Your ingress configuration should look something like this:

```yaml
## Ingress properties
ingress:
  useTls: true
  ui:
    enabled: true
    domain: "terrakube-ui.yourcustomdomain.com" # <--- Your real domain
    path: "/(.*)"
    pathType: "Prefix" 
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: letsencrypt
  api:
    enabled: true
    domain: "terrakube-api.yourcustomdomain.com" # <--- Your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt
  registry:
    enabled: true
    domain: "terrakube-reg.yourcustomdomain.com" # <--- Your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt
  dex:
    enabled: true
    path: "/dex/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt
```
The terrakube components should look something like this in your helm chart:

```yaml
## API properties
api:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    databaseType: "H2"

## Executor properties
executor:
  enabled: true
  version: "2.10.0"  
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"

## Registry properties
registry:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"

## UI Properties
ui:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
```

**Reply by erick-prosimo** [reply]
Everything is there except the NGINX ingress. I'm going to remove the current installation, add that ingress first, and then re-deploy. Do the DNS names need to be publicly resolvable?

**Reply by alfespa17** [reply]
To be honest I always use a public DNS because to use the terraform registry in Terrakube the ***Terraform CLI require a valid TLS certificate*** so I generate one using Lets Encrypt certificates for my K8S cluster,  But it should work wih a private DNS as long as Terrakube pods are able to resolve the other component URL. 

If you are using some private/internal DNS I think you will want to add your CA certs so you can have a valid TLS cert, if that is the case you can refer to the following [issue](https://github.com/AzBuilder/terrakube-helm-chart/issues/36)

**Reply by erick-prosimo** [reply]
Looking at your nginx build I do see cert-manager and webhook are not part of the nginx helm chart I deployed. I assume those services are also needed.

**Reply by erick-prosimo** [reply]
Maybe providing an NGINX helm chart with values needed to support Terrakube would be a good idea ;-)

**Reply by alfespa17** [reply]
That is correct I use ngnix-ingress and cert manager in my installation because I use lets encrypt for the TLS certificates

Microsoft provide some documentation to do this, you can find the information in this link.
https://learn.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli
https://learn.microsoft.com/en-us/azure/aks/ingress-tls?tabs=azure-cli

If you are using Nginx ingress like me you basically need to do the following using your K8S and your azure container registry:

# Import Nginx images to your Azure Container Registry
```bash
REGISTRY_NAME=<REGISTRY_NAME>
SOURCE_REGISTRY=k8s.gcr.io
CONTROLLER_IMAGE=ingress-nginx/controller
CONTROLLER_TAG=v1.2.1
PATCH_IMAGE=ingress-nginx/kube-webhook-certgen
PATCH_TAG=v1.1.1
DEFAULTBACKEND_IMAGE=defaultbackend-amd64
DEFAULTBACKEND_TAG=1.5

az acr import --name $REGISTRY_NAME --source $SOURCE_REGISTRY/$CONTROLLER_IMAGE:$CONTROLLER_TAG --image $CONTROLLER_IMAGE:$CONTROLLER_TAG
az acr import --name $REGISTRY_NAME --source $SOURCE_REGISTRY/$PATCH_IMAGE:$PATCH_TAG --image $PATCH_IMAGE:$PATCH_TAG
az acr import --name $REGISTRY_NAME --source $SOURCE_REGISTRY/$DEFAULTBACKEND_IMAGE:$DEFAULTBACKEND_TAG --image $DEFAULTBACKEND_IMAGE:$DEFAULTBACKEND_TAG
```

# Install Nginx In your AKS.

```bash
REGISTRY_NAME=<REGISTRY_NAME>
SOURCE_REGISTRY=k8s.gcr.io
CONTROLLER_IMAGE=ingress-nginx/controller
CONTROLLER_TAG=v1.2.1
PATCH_IMAGE=ingress-nginx/kube-webhook-certgen
PATCH_TAG=v1.1.1
DEFAULTBACKEND_IMAGE=defaultbackend-amd64
DEFAULTBACKEND_TAG=1.5

# Add the ingress-nginx repository
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

# Set variable for ACR location to use for pulling images
ACR_URL=<REGISTRY_NAME>.azurecr.io

# Use Helm to deploy an NGINX ingress controller
helm install nginx-ingress ingress-nginx/ingress-nginx \
    --version 4.1.3 \
    --namespace ingress-basic \
    --create-namespace \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.image.registry=$ACR_URL \
    --set controller.image.image=$CONTROLLER_IMAGE \
    --set controller.image.tag=$CONTROLLER_TAG \
    --set controller.image.digest="" \
    --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
    --set controller.admissionWebhooks.patch.image.registry=$ACR_URL \
    --set controller.admissionWebhooks.patch.image.image=$PATCH_IMAGE \
    --set controller.admissionWebhooks.patch.image.tag=$PATCH_TAG \
    --set controller.admissionWebhooks.patch.image.digest="" \
    --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
    --set defaultBackend.image.registry=$ACR_URL \
    --set defaultBackend.image.image=$DEFAULTBACKEND_IMAGE \
    --set defaultBackend.image.tag=$DEFAULTBACKEND_TAG \
    --set defaultBackend.image.digest=""
```

# Check IP from Nginx Ingress

Using the following command:

```bash
kubectl get services --namespace ingress-basic -o wide -w ingress-nginx-controller

NAME                       TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
ingress-nginx-controller   LoadBalancer   10.0.65.205   EXTERNAL-IP     80:30957/TCP,443:32414/TCP   1m   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
```

Use the external IP to update your DNS records using A records for the terrakube components:
Api: terrakube-api.myterrakube.com
Registry: terrakube-reg.myterrakube.com
Dex: terrakube-api.myterrakube.com/dex

# Import cert manager images to your azure container registry if you like to use Lets Encrypt

```bash
REGISTRY_NAME=<REGISTRY_NAME>
CERT_MANAGER_REGISTRY=quay.io
CERT_MANAGER_TAG=v1.8.2
CERT_MANAGER_IMAGE_CONTROLLER=jetstack/cert-manager-controller
CERT_MANAGER_IMAGE_WEBHOOK=jetstack/cert-manager-webhook
CERT_MANAGER_IMAGE_CAINJECTOR=jetstack/cert-manager-cainjector

az acr import --name $REGISTRY_NAME --source $CERT_MANAGER_REGISTRY/$CERT_MANAGER_IMAGE_CONTROLLER:$CERT_MANAGER_TAG --image $CERT_MANAGER_IMAGE_CONTROLLER:$CERT_MANAGER_TAG
az acr import --name $REGISTRY_NAME --source $CERT_MANAGER_REGISTRY/$CERT_MANAGER_IMAGE_WEBHOOK:$CERT_MANAGER_TAG --image $CERT_MANAGER_IMAGE_WEBHOOK:$CERT_MANAGER_TAG
az acr import --name $REGISTRY_NAME --source $CERT_MANAGER_REGISTRY/$CERT_MANAGER_IMAGE_CAINJECTOR:$CERT_MANAGER_TAG --image $CERT_MANAGER_IMAGE_CAINJECTOR:$CERT_MANAGER_TAG
```

# Install cert manager
```bash
REGISTRY_NAME=<REGISTRY_NAME>
CERT_MANAGER_REGISTRY=quay.io
CERT_MANAGER_TAG=v1.8.2
CERT_MANAGER_IMAGE_CONTROLLER=jetstack/cert-manager-controller
CERT_MANAGER_IMAGE_WEBHOOK=jetstack/cert-manager-webhook
CERT_MANAGER_IMAGE_CAINJECTOR=jetstack/cert-manager-cainjector

# Set variable for ACR location to use for pulling images
ACR_URL=<REGISTRY_NAME>.azurecr.io

# Label the ingress-basic namespace to disable resource validation
kubectl label namespace ingress-basic cert-manager.io/disable-validation=true

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

# Install the cert-manager Helm chart
helm install cert-manager jetstack/cert-manager \
  --namespace ingress-basic \
  --version $CERT_MANAGER_TAG \
  --set installCRDs=true \
  --set nodeSelector."kubernetes\.io/os"=linux \
  --set image.repository=$ACR_URL/$CERT_MANAGER_IMAGE_CONTROLLER \
  --set image.tag=$CERT_MANAGER_TAG \
  --set webhook.image.repository=$ACR_URL/$CERT_MANAGER_IMAGE_WEBHOOK \
  --set webhook.image.tag=$CERT_MANAGER_TAG \
  --set cainjector.image.repository=$ACR_URL/$CERT_MANAGER_IMAGE_CAINJECTOR \
  --set cainjector.image.tag=$CERT_MANAGER_TAG
```

# CA cluster issuer
```bash
kubectl apply -f cluster-issuer.yaml --namespace ingress-basic
```
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: MY_EMAIL_ADDRESS
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
```

Once the ingress setup is completed you can install the terrakube helm chart.

**Reply by alfespa17** [reply]
The above will only apply if you use AKS+Azure Container Registry+NginxIngress+LetsEncrypt. 

If you would like to use other ingress or cloud provider the setup will be completly different.

**Reply by erick-prosimo** [reply]
OK, so this also requires ACR. I mean, you can see why this is frustrating considering none of this is called out in the deployment guide for Terrakube. The sample deployment charts have other dependencies, and I think the expectation would be if there are dependencies in those charts they are called out.

**Reply by alfespa17** [reply]
Yes I understand your point, we will have to update the deployment guide and add some additional information.

Our mistake was to assume the ingress setup is completed in your Kubernetes environment  before installing Terrakube helm chart

**Reply by erick-prosimo** [reply]
First of all, thank you so much for assisting. Secondly, there is another step that needs to happen, and that is allowing the AKS cluster to authenticate to the ACR that is setup. 

I have made a lot of progress, but am now hitting an issue with DEX. I have the AAD identity setup with the correct redirect URI, but I did have questions around 2 settings in the helm values for Terrakube.

I see there are 2 settings, patSecret and internalSecret. What are these? 

And for the AAD service principal (I do have the correct permissions for user.read and directory.read.all, along with granting admin consent), but are there any additional claims that need to be added to the principal for token configuration?

I'm just getting a very generic error from DEX: Internal Server Error
Login error.

**Reply by alfespa17** [reply]
In terrakube you can generate ***Personal Access Tokens***, we use ***patSecret*** as the password to sign the tokens that we provide to the users. We use this PAT so the terraform cli can authenticate with the private registry, you can also use the PAT token to call the API using postman form example. 

InternalSecret is a password to sign the token used for the internal components communication.

I am using the following dex setup in my helm chart:

```yaml
security:
  adminGroup: "MY_AD_GROUP_ADMIN"
  patSecret: "XXXXXXX"
  internalSecret: "XXXXXXXXX"
  dexClientId: "microsoft"
  dexClientScope: "email openid profile offline_access groups"
  dexIssuerUri: "https://terrakube-api.yourdomain.com/dex"
```

```yaml
dex:
  enabled: true
  version: "v2.32.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  resources:
    limits:
      cpu: 512m
      memory: 256Mi
    requests:
      cpu: 256m
      memory: 128Mi
  properties:
    config:
      issuer: https://terrakube-api.yourdomain.com/dex
      storage:
        type: memory
      oauth2:
        responseTypes: ["code", "token", "id_token"] 
        skipApprovalScreen: true
      web:
        allowedOrigins: ['*']
  
      staticClients:
      - id: microsoft
        redirectURIs:
        - 'https://terrakube-ui.yourdomain.com'
        - 'http://localhost:3000'
        - 'http://localhost:10001/login'
        - 'http://localhost:10000/login'
        - '/device/callback'
        name: 'microsoft'
        public: true

      connectors:
      - type: microsoft
        id: microsoft
        name: microsoft
        config:
          clientID: "XXXXXXXXXX"
          clientSecret: "XXXXXXXXX"
          redirectURI: "https://terrakube-api.yourdomain.com/dex/callback"
          tenant: "XXXXXXX"
```

App Registration Config:

![image](https://user-images.githubusercontent.com/4461895/216065514-2853d29f-a460-426c-a44e-fb8b2cb3dc78.png)

![image](https://user-images.githubusercontent.com/4461895/216065646-582f1be0-051f-40da-8e96-398824df86f9.png)

![image](https://user-images.githubusercontent.com/4461895/216065810-4c82a067-ef6d-4213-8402-3aad3165f413.png)

Dex configuration reference can be found [here](https://dexidp.io/docs/connectors/microsoft/)

You could check the logs from the dex pod, here is an example how you can see thos logs.

```bash
kubeclt get pods -n terrakube
kubectl logs terrakube-dex-547dbc7598-7t9mk -n terrakube
```

![image](https://user-images.githubusercontent.com/4461895/216067784-e7c24d33-b2f1-4694-bfc3-a9c587a59a5c.png)

![image](https://user-images.githubusercontent.com/4461895/216068037-a38ed28d-83aa-4842-a257-3b6d82cdc2f2.png)
