### DISCUSSION TITLE
Terrakube on GKE exposed with GCP Loadbalancer

### DISCUSSION THREAD

**Discussion by jmorenog** [terrakube-io/terrakube#388] [Q&A] [answered]
Hi Folks, somebody lknow if it possible to expose terrakube deployed over gke, with a GCP load balancer???

**Comment by alfespa17** [comment, marked as answer]
Hello @jmorenog there was an issue about that sometime ago, maybe you can check here:

https://github.com/AzBuilder/terrakube-helm-chart/issues/61

I think you need to use something like this when deploying the helm chart values, the service type should be NodePort and use the gke ingress annotations

```yaml
## API properties
api:
  serviceType: "NodePort"

## Executor properties
executor:
  serviceType: "NodePort"

## Registry properties
registry:
  serviceType: "NodePort"

## Registry properties
registry:
  serviceType: "NodePort"

## Ingress properties
ingress:
  useTls: true
  includeTlsHosts: false
  ui:
    enabled: true
    domain: "terrakube-ui.minikube.net"
    path: "/"
    pathType: "ImplementationSpecific" 
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
  api:
    enabled: true
    domain: "terrakube-api.minikube.net"
    path: "/"
    pathType: "ImplementationSpecific"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
  registry:
    enabled: true
    domain: "terrakube-reg.minikube.net"
    path: "/"
    pathType: "ImplementationSpecific"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
  dex:
    enabled: true
    path: "/dex/"
    pathType: "ImplementationSpecific"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
```

If you find any problem feel free to create an issue in the helm chart repository 

https://github.com/AzBuilder/terrakube-helm-chart/issues

we can create a fix if need it so you can deploy it without any issues in gke
