### DISCUSSION TITLE
Terrakube on EKS with nginx-ingress

### DISCUSSION THREAD

**Discussion by jderieg** [terrakube-io/terrakube#397] [Q&A] [answered]
Hi there, I have an EKS cluster with nginx-ingress already installed. I'm trying to install Terrakube (using the helm chart), and I've used the values provided by the terrakube docs for the ingress setup. This is what mine looks like, you'll notice it's very similar to the setup in the docs:

```
...
## Ingress properties
ingress:
  useTls: false
  ui:
    enabled: true
    domain: "terrakube-ui.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
  api:
    enabled: true
    domain: "terrakube-api.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
  registry:
    enabled: true
    domain: "terrakube-reg.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
  dex:
    enabled: true
    path: "/dex/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
```

The helm chart installs fine, and the configuration gets written to my conf.d directory on the nginx-ingress pod. However, whenever I call `terrakube-ui.example.com` for example, it seems that nginx-ingress wants to tack on `/etc/nginx/http/` to the URL path. 

For example, if I were to call `http://terrakube-ui.example.com/login`, nginx-ingress would rewrite that URL as http://terrakube-ui.example.com/etc/nginx/http/login`, and I'm not entirely sure why. I don't see anything in the nginx config that should be doing that. Any ideas or suggestions would be appreciated.

The values file I'm using for the nginx-ingress controller helm chart are really simple. These are the only settings I'm modifying off the base install:

```
controller:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
  disableIPV6: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
```

**Comment by alfespa17** [comment]
Hello @jderieg 

What is the helm chart and terrakube version that you are using?

**Reply by jderieg** [reply]
The helm chart version for Terrakube I'm using is 3.5.1. The helm chart version for nginx-ingress is 0.17.1. I believe both of those are the latest.

**Reply by alfespa17** [reply]
I think the latest ngnix ingress helm chart is this one https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.7.0 not 0.17.1

**Reply by jderieg** [reply]
I'm using the official Nginx helm release, for which the latest version is 0.17.1: https://github.com/nginxinc/kubernetes-ingress/tree/v3.1.1/deployments/helm-chart

**Reply by alfespa17** [reply]
Not sure about that version, maybe you could check this AWS docs, maybe it can help you.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus-Sample-Workloads-nginx.html

**Reply by jderieg** [reply]
OK, I'll test out a cluster using that nginx ingress instead of the official one and see if it works.

**Reply by jderieg** [reply]
Thanks for the suggestion! With the kubernetes version of ingress-nginx, it seems to work. I can now get to my terraform-ui page in a browser. However, when I hit the Login button, nothing happens.
Checking the developer console in the browser, I see the following error:
"MetadataService.ts:53 Uncaught (in promise) Error: No authority or metadataUrl configured on settings"

I'm pretty sure I have all my settings correct in my values file for the helm chart. Here's my entire values file. Let me know if you see anything misconfigured or if you have any other ideas why I might be getting that error:

```
## Global Name
name: "terrakube"

## Terrakube Security
security:
  adminGroup: ${terrakube_gh_group} # This should be your Github team the format is OrganizationName:TeamName
  patSecret: ${terrakube_dex_pat}  # Sample Key 32 characters z6QHX!y@Nep2QDT!53vgH43^PjRXyC3X
  internalSecret: ${terrakube_dex_internal} # Sample Key 32 characters Kb^8cMerPNZV6hS!9!kcD*KuUPUBa^B3
  dexClientId: "github"
  dexClientScope: "email openid profile offline_access groups"
  dexIssuerUri: "https://terrakube-api.${terrakube_dnsdomain}/dex" # Change for your real domain

## Terraform Storage
storage:
  aws:
    accessKey: ${awskey}
    secretKey: ${awssecret}
    bucketName: "${environment_letter_tag}-terrakube"
    region: "us-east-2"

dex:
  enabled: true
  version: "v2.32.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  resources:
    limits:
      cpu: 512m
      memory: 256Mi
    requests:
      cpu: 256m
      memory: 128Mi
  properties:
    config:
      issuer: https://terrakube-api.${terrakube_dnsdomain}/dex
      storage:
        type: memory
      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true
      web:
        allowedOrigins: ["*"]

      staticClients:
        - id: github
          redirectURIs:
            - 'https://terrakube-ui.${terrakube_dnsdomain}'
            - 'http://localhost:10001/login'
            - 'http://localhost:10000/login'
            - '/device/callback'
          name: 'github'
          public: true

      connectors:
        - type: github
          id: github
          name: gitHub
          config:
            clientID: "96bc73d25bfb9bee186d"
            clientSecret: ${terrakube_gh_clientsecret}
            redirectURI: "https://terrakube-api.${terrakube_dnsdomain}/dex/callback"
            loadAllGroups: true

## API properties
api:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    databaseType: "H2"

## Executor properties
executor:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"

## Registry properties
registry:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"

## UI Properties
ui:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"

## Ingress properties
ingress:
  useTls: true
  ui:
    enabled: true
    domain: "terrakube-ui.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
  api:
    enabled: true
    domain: "terrakube-api.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
  registry:
    enabled: true
    domain: "terrakube-reg.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
  dex:
    enabled: true
    path: "/dex/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
```

**Reply by alfespa17** [reply]
Hello @jderieg 

I can see the problem, sometime ago we change how we handle the DEX configuration in the helm chart, You will have to do some small changes in the above values.yaml, let me show you some example.

Regards.

**Reply by alfespa17** [reply, marked as answer]
Hello @jderieg 

I think this values can work for you:

```yaml
## Global Name
name: "terrakube"

## Terrakube Security
security:
  useOpenLDAP: false
  adminGroup: ${terrakube_gh_group}
  patSecret: ${terrakube_dex_pat}  # Sample Key 32 characters z6QHX!y@Nep2QDT!53vgH43^PjRXyC3X
  internalSecret: ${terrakube_dex_internal} # Sample Key 32 characters Kb^8cMerPNZV6hS!9!kcD*KuUPUBa^B3
  dexClientId: "github"
  dexClientScope: "email openid profile offline_access groups"

## Terraform Storage
storage:
  aws:
    accessKey: ${awskey}
    secretKey: ${awssecret}
    bucketName: "${environment_letter_tag}-terrakube"
    region: "us-east-2"

dex:
  enabled: true
  config:
    issuer: https://terrakube-api.${terrakube_dnsdomain}/dex
    storage:
      type: memory
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true
    web:
      allowedOrigins: ["*"]

    staticClients:
    - id: github
      redirectURIs:
      - 'https://terrakube-ui.${terrakube_dnsdomain}'
      - 'http://localhost:10001/login'
      - 'http://localhost:10000/login'
      - '/device/callback'
      name: 'github'
      public: true

    connectors:
    - type: github
      id: github
      name: gitHub
      config:
        clientID: "96bc73d25bfb9bee186d"
        clientSecret: ${terrakube_gh_clientsecret}
        redirectURI: "https://terrakube-api.${terrakube_dnsdomain}/dex/callback"
        loadAllGroups: true

## Ingress properties
ingress:
  useTls: true
  ui:
    enabled: true
    domain: "terrakube-ui.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
  api:
    enabled: true
    domain: "terrakube-api.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
  registry:
    enabled: true
    domain: "terrakube-reg.${terrakube_dnsdomain}" # Change for your real domain
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
  dex:
    enabled: true
    path: "/dex/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      cert-manager.io/cluster-issuer: letsencrypt-${environment_tag}
```

I will have to update the docs, to reflect the current changes in the helm chart.

To see the latest structure you can always refer to the default values.yalm in this link.

https://github.com/AzBuilder/terrakube-helm-chart/blob/main/charts/terrakube/values.yaml

You only need to specify this section if you want to do some customization:
```yaml
## API properties
api:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    databaseType: "H2"

## Executor properties
executor:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"

## Registry properties
registry:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"

## UI Properties
ui:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
```

By default it will take the values from here:
https://github.com/AzBuilder/terrakube-helm-chart/blob/main/charts/terrakube/values.yaml#L157

I hope this can help you. Let me know if you face any other issue, I will be happy to help.
