### DISCUSSION TITLE
Getting CORS error while integrating AWS cognito

### DISCUSSION THREAD

**Discussion by abhinavsquadstack** [terrakube-io/terrakube#466] [Q&A]
Hello Team,
I am working on to integrate AWS cognito into my  terrakube setup using docker-compose. I have changed the config-ldap.yaml with AWS cognito connector config as given in the documentation. But after doing that I am getting CORS error. I am not able to resolve this and need help.

Before this, when I was using ldap(default setting), I was able to setup the whole terrakube application and was able to login and do other stuff.
Do i need to change anything here?
<img width="540" alt="image" src="https://github.com/AzBuilder/terrakube/assets/121935932/dfe50de2-c36b-4fad-a1a4-58e9aea69298">

My config-ldap.yaml(with cognito connector) file contents are:
```
## Dex
dex:
  enabled: true
  version: "v2.32.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  resources:
    limits:
      cpu: 512m
      memory: 256Mi
    requests:
      cpu: 256m
      memory: 128Mi
  properties:
    config:
      issuer: https://dex.terrakube.squadstack.link/dex
      storage:
        type: memory
      oauth2:
        responseTypes: ["code", "token", "id_token"] 
        skipApprovalScreen: true
      web:
        allowedOrigins: ["*"]
  
      staticClients:
      - id: cognito
        redirectURIs:
        - 'https://ui.terrakube.squadstack.link' 
        - '/device/callback'
        - 'http://localhost:10001/login'
        - 'http://localhost:10000/login'
        name: 'cognito'
        public: true

      connectors:
      - type: oidc
        id: cognito
        name: cognito
        config:
          issuer: "https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_XXXX"
          clientID: $clientID
          clientSecret: $clientSecret
          redirectURI: "https://dex.terrakube.squadstack.link/dex/callback"
          scopes:
            - openid
            - email
            - profile
          insecureSkipEmailVerified: true
          insecureEnableGroups: true
          userNameKey: "cognito:username"
          claimMapping: 
            groups: "cognito:groups"
```
