### DISCUSSION TITLE
Issues with API after Azure AD integration

### DISCUSSION THREAD

**Discussion by Ghoshaya1** [terrakube-io/terrakube#534] [Q&A] [answered]
We have done Azure (entra) AD integration with terrakube on k3s, but after logging in we are unable to access /create any organizations within on checking the API pod logs we get the following error has anyone faced similar issues. Need help on this.

logs from the API pod =============
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://terrakube-api/dex/.well-known/openid-configuration": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:676) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getConfiguration(JwtDecoderProviderConfigurationUtils.java:150) ~[spring-security-oauth2-jose-5.7.9.jar:5.7.9]
        ... 68 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[na:na]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782) ~[spring-web-5.3.28.jar:5.3.28]
        ... 70 common frames omitted

**Comment by alfespa17** [comment, marked as answer]
Hello @Ghoshaya1 

I don't have experience with k3s but I guess you are using some self signed certificate. In that case you will have to add your CA certificates at runtime, when you deploy the helm chart you will have to add some parameters.

You could check:

https://docs.terrakube.io/getting-started/deployment/custom-ca-certs
https://github.com/AzBuilder/terrakube-helm-chart#5-custom-ca-certificates-at-runtime

It will be something like this:

helm parameters:

```yaml
security:
  .....
  caCerts:
    terrakubeDemo1.pem: |
      -----BEGIN CERTIFICATE-----

      CERTIFICATE DATA

      -----END CERTIFICATE-----
    terrakubeDemo2.pem: |
      -----BEGIN CERTIFICATE-----

      CERTIFICATE DATA

      -----END CERTIFICATE-----
  ....

api:
  enabled: true
  replicaCount: "1"
  serviceType: "ClusterIP"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "terrakubeDemo1.pem"
          path: "terrakubeDemo1.pem"
        - key: "terrakubeDemo2.pem"
          path: "terrakubeDemo2.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true

registry:
  enabled: true
  replicaCount: "1"
  serviceType: "ClusterIP"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "terrakubeDemo1.pem"
          path: "terrakubeDemo1.pem"
        - key: "terrakubeDemo2.pem"
          path: "terrakubeDemo2.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true
```
