### ISSUE TITLE
Error after creating workspace with ssh

### ISSUE THREAD

**Issue by philsjh** [terrakube-io/terrakube#2225]
### Bug description 🐞

On creating a workspace using GitHub SSH as a source, an error appears:

```
Unexpected Application Error!
Failed to construct 'URL': Invalid URL
TypeError: Invalid URL
    at WorkspaceDetails (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:1484:64004)
    at Jl (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:31:18836)
    at Bd (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:33:3497)
    at C1 (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:33:49335)
    at sp (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:33:43727)
    at ip (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:33:43653)
    at Mf (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:33:43501)
    at Qu (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:33:39509)
    at o1 (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:33:38346)
    at Bt (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:18:1872)
    at MessagePort.Nr (https://terrakube-ui.**masked**/assets/index-DkXtk-3_.js:18:2275)
    
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```

JavaScript error console:

```
React Router caught the following error during render TypeError: Failed to construct 'URL': Invalid URL
    at WorkspaceDetails (index-DkXtk-3_.js:1484:64004)
    at Jl (index-DkXtk-3_.js:31:18836)
    at Bd (index-DkXtk-3_.js:33:3497)
    at C1 (index-DkXtk-3_.js:33:49335)
    at sp (index-DkXtk-3_.js:33:43727)
    at ip (index-DkXtk-3_.js:33:43653)
    at Mf (index-DkXtk-3_.js:33:43501)
    at Qu (index-DkXtk-3_.js:33:39509)
    at o1 (index-DkXtk-3_.js:33:38346)
    at Bt (index-DkXtk-3_.js:18:1872)
    at MessagePort.Nr (index-DkXtk-3_.js:18:2275) {componentStack: '\n    at WorkspaceDetails (https://terrakube-ui.mask…edurl/assets/index-DkXtk-3_.js:33:135441)'}
```

### Steps to reproduce

Create a workspace, use OpenTofu, version 1.9.1, github SSH as a remote.

### Expected behavior

It should take me to the workspace homepage.

### Anything else?

Using the helm chart, argo config below - current app version is 2.26.2:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terrakube
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
    environment: production
spec:
  project: terrakube
  source:
    chart: terrakube
    repoURL: https://AzBuilder.github.io/terrakube-helm-chart
    targetRevision: 3.27.4
```
